import { Opportunity } from "./types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "op1",
    title: "Frontend Developer",
    company: "Google",
    location: "Bangalore",
    type: "Job",
    description: "Looking for a passionate frontend developer with React experience. Navodayans preferred — we value the grit and determination that JNV background brings.",
    requirements: ["3+ years React", "TypeScript", "System Design basics"],
    postedBy: "1",
    postedByName: "Rahul Sharma",
    postedAt: "2026-03-20",
    contactEmail: "rahul.sharma@email.com",
    applyUrl: "https://careers.google.com",
    isRemote: false,
    salary: "₹18-25 LPA",
  },
  {
    id: "op2",
    title: "Summer Research Intern",
    company: "AIIMS Delhi",
    location: "New Delhi",
    type: "Internship",
    description: "Research internship in public health data analysis. Great opportunity for pre-med or biotech students from JNV background.",
    requirements: ["Currently pursuing MBBS/BSc", "Basic statistics", "MS Excel proficiency"],
    postedBy: "2",
    postedByName: "Priya Patel",
    postedAt: "2026-03-18",
    contactEmail: "priya.patel@email.com",
    isRemote: false,
  },
  {
    id: "op3",
    title: "Startup Co-Founder (Tech)",
    company: "TechStart India",
    location: "Mumbai",
    type: "Freelance",
    description: "Looking for a technical co-founder for an EdTech startup focused on rural education. Equity-based compensation.",
    requirements: ["Full-stack development", "Startup mindset", "Passion for education"],
    postedBy: "3",
    postedByName: "Amit Kumar",
    postedAt: "2026-03-15",
    contactEmail: "amit.kumar@email.com",
    isRemote: true,
  },
  {
    id: "op4",
    title: "Data Science Mentorship",
    company: "Microsoft",
    location: "Hyderabad",
    type: "Mentorship",
    description: "Offering 1-on-1 mentorship for JNV alumni interested in breaking into Data Science and AI/ML. 3-month structured program.",
    requirements: ["Basic Python knowledge", "Interest in AI/ML", "Commitment to weekly sessions"],
    postedBy: "4",
    postedByName: "Sneha Reddy",
    postedAt: "2026-03-22",
    contactEmail: "sneha.reddy@email.com",
    isRemote: true,
  },
  {
    id: "op5",
    title: "UPSC Preparation Guidance",
    company: "Government of India",
    location: "Pan India",
    type: "Mentorship",
    description: "Free UPSC mentorship for JNV alumni. Covering strategy, optional selection, answer writing, and interview preparation.",
    requirements: ["Graduated or final year", "Serious about civil services", "Willing to commit 6 months"],
    postedBy: "5",
    postedByName: "Vikram Singh",
    postedAt: "2026-03-10",
    contactEmail: "vikram.singh@email.com",
    isRemote: true,
  },
  {
    id: "op6",
    title: "Legal Intern",
    company: "Supreme Court of India",
    location: "New Delhi",
    type: "Internship",
    description: "Internship opportunity at a leading law chamber. Focus on constitutional law and human rights cases.",
    requirements: ["Pursuing LLB/BA LLB", "Strong research skills", "Good writing ability"],
    postedBy: "6",
    postedByName: "Kavita Mishra",
    postedAt: "2026-03-12",
    contactEmail: "kavita.mishra@email.com",
    isRemote: false,
    salary: "₹15,000/month stipend",
  },
];
