import { Alumni } from "./types";

export const mockAlumni: Alumni[] = [
  {
    id: "1",
    fullName: "Rahul Sharma",
    batch: 2010,
    house: "Shivalik",
    profession: "Software Engineer",
    companyName: "Google",
    currentCity: "Bangalore",
    helpOffered: ["Mentorship", "Career Guidance"],
    bio: "Passionate about technology and helping juniors navigate their career in tech. Love to mentor students from JNV background.",
    photoUrl: "",
    email: "rahul.sharma@email.com",
    phone: "+91 98765 43210",
    approved: true,
  },
  {
    id: "2",
    fullName: "Priya Patel",
    batch: 2012,
    house: "Nilgiri",
    profession: "Doctor",
    companyName: "AIIMS Delhi",
    currentCity: "New Delhi",
    helpOffered: ["Career Guidance", "Mentorship"],
    bio: "MBBS from AIIMS, currently working as a resident doctor. Happy to guide aspiring medical students.",
    photoUrl: "",
    email: "priya.patel@email.com",
    approved: true,
  },
  {
    id: "3",
    fullName: "Amit Kumar",
    batch: 2008,
    house: "Aravali",
    profession: "Entrepreneur",
    companyName: "TechStart India",
    currentCity: "Mumbai",
    helpOffered: ["Business Advice", "Jobs"],
    bio: "Founded my startup after IIT. Building solutions for rural education. Always open to connecting with fellow Navodayans.",
    photoUrl: "",
    email: "amit.kumar@email.com",
    approved: true,
  },
  {
    id: "4",
    fullName: "Sneha Reddy",
    batch: 2015,
    house: "Udaygiri",
    profession: "Data Scientist",
    companyName: "Microsoft",
    currentCity: "Hyderabad",
    helpOffered: ["Mentorship", "Jobs"],
    bio: "Working in AI/ML at Microsoft. Passionate about using data for social good.",
    photoUrl: "",
    email: "sneha.reddy@email.com",
    approved: true,
  },
  {
    id: "5",
    fullName: "Vikram Singh",
    batch: 2005,
    house: "Shivalik",
    migrationJnv: "JNV Jaipur",
    profession: "IAS Officer",
    companyName: "Government of India",
    currentCity: "Lucknow",
    helpOffered: ["Career Guidance", "Mentorship"],
    bio: "UPSC 2011 batch. Serving as District Magistrate. Want to help JNV students crack civil services.",
    photoUrl: "",
    email: "vikram.singh@email.com",
    approved: true,
  },
  {
    id: "6",
    fullName: "Kavita Mishra",
    batch: 2014,
    house: "Nilgiri",
    profession: "Lawyer",
    companyName: "Supreme Court of India",
    currentCity: "New Delhi",
    helpOffered: ["Career Guidance", "Business Advice"],
    bio: "Practicing advocate at the Supreme Court. Interested in legal aid and human rights.",
    photoUrl: "",
    email: "kavita.mishra@email.com",
    approved: true,
  },
];
